import { drizzle } from 'drizzle-orm/libsql';
import { createClient } from '@libsql/client';
import { breaks, conditions, userBreaks } from './schema';
import { nanoid } from 'nanoid';
import { sql } from 'drizzle-orm';

const client = createClient({
  url: process.env.TURSO_DATABASE_URL ?? 'file:local.db',
  authToken: process.env.TURSO_AUTH_TOKEN,
});

const db = drizzle(client);

// Southern California surf breaks with accurate metadata
// Orientation = direction the break faces (where waves come FROM to hit the beach)
// Optimal swell dir = swell direction range that produces best waves
// Wind dir = offshore direction for the break (opposite of orientation)
const SOCAL_BREAKS: Array<{
  name: string;
  region: string;
  latitude: number;
  longitude: number;
  orientationDeg: number;
  breakType: 'beach' | 'reef' | 'point';
  optimalSwellDirMin: number;
  optimalSwellDirMax: number;
  optimalWindDir: string;
  optimalTideLow: number;
  optimalTideHigh: number;
  nearestTideStation: string;
  nearestBuoyStation: string;
  exposureFactor: number;
}> = [
  // --- San Diego County ---
  {
    name: 'Blacks Beach',
    region: 'San Diego',
    latitude: 32.8894,
    longitude: -117.2530,
    orientationDeg: 270,
    breakType: 'beach',
    optimalSwellDirMin: 250,
    optimalSwellDirMax: 310,
    optimalWindDir: 'E',
    optimalTideLow: -0.5,
    optimalTideHigh: 3.0,
    nearestTideStation: '9410230', // La Jolla
    nearestBuoyStation: '46225',
    exposureFactor: 0.9,
  },
  {
    name: 'Windansea',
    region: 'San Diego',
    latitude: 32.8304,
    longitude: -117.2818,
    orientationDeg: 260,
    breakType: 'reef',
    optimalSwellDirMin: 240,
    optimalSwellDirMax: 300,
    optimalWindDir: 'E',
    optimalTideLow: 0.0,
    optimalTideHigh: 3.0,
    nearestTideStation: '9410230',
    nearestBuoyStation: '46225',
    exposureFactor: 0.85,
  },
  {
    name: 'Ocean Beach Pier',
    region: 'San Diego',
    latitude: 32.7491,
    longitude: -117.2538,
    orientationDeg: 250,
    breakType: 'beach',
    optimalSwellDirMin: 230,
    optimalSwellDirMax: 290,
    optimalWindDir: 'ENE',
    optimalTideLow: -0.5,
    optimalTideHigh: 4.0,
    nearestTideStation: '9410170', // San Diego
    nearestBuoyStation: '46225',
    exposureFactor: 0.85,
  },
  {
    name: 'Sunset Cliffs',
    region: 'San Diego',
    latitude: 32.7198,
    longitude: -117.2565,
    orientationDeg: 245,
    breakType: 'reef',
    optimalSwellDirMin: 220,
    optimalSwellDirMax: 280,
    optimalWindDir: 'ENE',
    optimalTideLow: 0.5,
    optimalTideHigh: 3.5,
    nearestTideStation: '9410170',
    nearestBuoyStation: '46225',
    exposureFactor: 0.85,
  },
  {
    name: 'Cardiff Reef',
    region: 'San Diego',
    latitude: 33.0186,
    longitude: -117.2916,
    orientationDeg: 255,
    breakType: 'reef',
    optimalSwellDirMin: 230,
    optimalSwellDirMax: 290,
    optimalWindDir: 'E',
    optimalTideLow: 1.0,
    optimalTideHigh: 4.0,
    nearestTideStation: '9410230',
    nearestBuoyStation: '46225',
    exposureFactor: 0.85,
  },
  {
    name: 'Swamis',
    region: 'San Diego',
    latitude: 33.0339,
    longitude: -117.2933,
    orientationDeg: 250,
    breakType: 'reef',
    optimalSwellDirMin: 220,
    optimalSwellDirMax: 280,
    optimalWindDir: 'E',
    optimalTideLow: 0.5,
    optimalTideHigh: 3.5,
    nearestTideStation: '9410230',
    nearestBuoyStation: '46225',
    exposureFactor: 0.85,
  },
  {
    name: 'Oceanside Pier',
    region: 'San Diego',
    latitude: 33.1937,
    longitude: -117.3918,
    orientationDeg: 250,
    breakType: 'beach',
    optimalSwellDirMin: 220,
    optimalSwellDirMax: 290,
    optimalWindDir: 'E',
    optimalTideLow: -0.5,
    optimalTideHigh: 4.0,
    nearestTideStation: '9410580', // La Jolla (Scripps Pier)
    nearestBuoyStation: '46225',
    exposureFactor: 0.85,
  },
  // --- Orange County ---
  {
    name: 'Trestles (Lowers)',
    region: 'Orange County',
    latitude: 33.3828,
    longitude: -117.5889,
    orientationDeg: 220,
    breakType: 'point',
    optimalSwellDirMin: 180,
    optimalSwellDirMax: 250,
    optimalWindDir: 'NE',
    optimalTideLow: 0.0,
    optimalTideHigh: 4.0,
    nearestTideStation: '9410580',
    nearestBuoyStation: '46224',
    exposureFactor: 0.85,
  },
  {
    name: 'Trestles (Uppers)',
    region: 'Orange County',
    latitude: 33.3856,
    longitude: -117.5895,
    orientationDeg: 225,
    breakType: 'point',
    optimalSwellDirMin: 190,
    optimalSwellDirMax: 260,
    optimalWindDir: 'NE',
    optimalTideLow: 0.5,
    optimalTideHigh: 4.5,
    nearestTideStation: '9410580',
    nearestBuoyStation: '46224',
    exposureFactor: 0.85,
  },
  {
    name: 'Salt Creek',
    region: 'Orange County',
    latitude: 33.4673,
    longitude: -117.7237,
    orientationDeg: 210,
    breakType: 'point',
    optimalSwellDirMin: 180,
    optimalSwellDirMax: 240,
    optimalWindDir: 'NE',
    optimalTideLow: 0.0,
    optimalTideHigh: 3.5,
    nearestTideStation: '9410580',
    nearestBuoyStation: '46224',
    exposureFactor: 0.85,
  },
  {
    name: 'The Wedge',
    region: 'Orange County',
    latitude: 33.5930,
    longitude: -117.8821,
    orientationDeg: 195,
    breakType: 'beach',
    optimalSwellDirMin: 160,
    optimalSwellDirMax: 220,
    optimalWindDir: 'N',
    optimalTideLow: -0.5,
    optimalTideHigh: 2.5,
    nearestTideStation: '9410580',
    nearestBuoyStation: '46224',
    exposureFactor: 0.95,
  },
  {
    name: 'Newport Beach (Blackies)',
    region: 'Orange County',
    latitude: 33.6057,
    longitude: -117.9297,
    orientationDeg: 210,
    breakType: 'beach',
    optimalSwellDirMin: 180,
    optimalSwellDirMax: 250,
    optimalWindDir: 'NE',
    optimalTideLow: -0.5,
    optimalTideHigh: 4.0,
    nearestTideStation: '9410580',
    nearestBuoyStation: '46224',
    exposureFactor: 0.85,
  },
  {
    name: 'HB Pier (Huntington Beach)',
    region: 'Orange County',
    latitude: 33.6553,
    longitude: -118.0050,
    orientationDeg: 210,
    breakType: 'beach',
    optimalSwellDirMin: 180,
    optimalSwellDirMax: 260,
    optimalWindDir: 'NE',
    optimalTideLow: -0.5,
    optimalTideHigh: 4.0,
    nearestTideStation: '9410580',
    nearestBuoyStation: '46224',
    exposureFactor: 0.85,
  },
  // --- LA County (South Bay / Malibu) ---
  {
    name: 'El Porto',
    region: 'Los Angeles',
    latitude: 33.8968,
    longitude: -118.4210,
    orientationDeg: 240,
    breakType: 'beach',
    optimalSwellDirMin: 210,
    optimalSwellDirMax: 280,
    optimalWindDir: 'E',
    optimalTideLow: -0.5,
    optimalTideHigh: 4.0,
    nearestTideStation: '9410660', // Los Angeles
    nearestBuoyStation: '46222',
    exposureFactor: 0.85,
  },
  {
    name: 'Manhattan Beach',
    region: 'Los Angeles',
    latitude: 33.8847,
    longitude: -118.4130,
    orientationDeg: 240,
    breakType: 'beach',
    optimalSwellDirMin: 210,
    optimalSwellDirMax: 270,
    optimalWindDir: 'E',
    optimalTideLow: -0.5,
    optimalTideHigh: 4.0,
    nearestTideStation: '9410660',
    nearestBuoyStation: '46222',
    exposureFactor: 0.85,
  },
  {
    name: 'Venice Breakwater',
    region: 'Los Angeles',
    latitude: 33.9847,
    longitude: -118.4777,
    orientationDeg: 240,
    breakType: 'beach',
    optimalSwellDirMin: 210,
    optimalSwellDirMax: 280,
    optimalWindDir: 'E',
    optimalTideLow: 0.0,
    optimalTideHigh: 4.0,
    nearestTideStation: '9410660',
    nearestBuoyStation: '46222',
    exposureFactor: 0.85,
  },
  {
    name: 'Topanga',
    region: 'Los Angeles',
    latitude: 34.0389,
    longitude: -118.5828,
    orientationDeg: 210,
    breakType: 'point',
    optimalSwellDirMin: 180,
    optimalSwellDirMax: 250,
    optimalWindDir: 'NE',
    optimalTideLow: 0.5,
    optimalTideHigh: 3.5,
    nearestTideStation: '9410660',
    nearestBuoyStation: '46222',
    exposureFactor: 0.75,
  },
  {
    name: 'Malibu (Surfrider)',
    region: 'Los Angeles',
    latitude: 34.0363,
    longitude: -118.6793,
    orientationDeg: 180,
    breakType: 'point',
    optimalSwellDirMin: 170,
    optimalSwellDirMax: 230,
    optimalWindDir: 'N',
    optimalTideLow: 1.0,
    optimalTideHigh: 4.0,
    nearestTideStation: '9410660',
    nearestBuoyStation: '46222',
    exposureFactor: 0.75,
  },
  {
    name: 'Zuma Beach',
    region: 'Los Angeles',
    latitude: 34.0258,
    longitude: -118.8225,
    orientationDeg: 200,
    breakType: 'beach',
    optimalSwellDirMin: 180,
    optimalSwellDirMax: 250,
    optimalWindDir: 'N',
    optimalTideLow: -0.5,
    optimalTideHigh: 4.0,
    nearestTideStation: '9410660',
    nearestBuoyStation: '46222',
    exposureFactor: 0.85,
  },
  {
    name: 'County Line',
    region: 'Los Angeles',
    latitude: 34.0501,
    longitude: -118.9629,
    orientationDeg: 195,
    breakType: 'point',
    optimalSwellDirMin: 170,
    optimalSwellDirMax: 240,
    optimalWindDir: 'N',
    optimalTideLow: 0.5,
    optimalTideHigh: 4.0,
    nearestTideStation: '9410660',
    nearestBuoyStation: '46222',
    exposureFactor: 0.75,
  },
  // --- Ventura County ---
  {
    name: 'Rincon',
    region: 'Ventura',
    latitude: 34.3739,
    longitude: -119.4782,
    orientationDeg: 180,
    breakType: 'point',
    optimalSwellDirMin: 170,
    optimalSwellDirMax: 230,
    optimalWindDir: 'N',
    optimalTideLow: 1.0,
    optimalTideHigh: 4.0,
    nearestTideStation: '9411340', // Santa Barbara
    nearestBuoyStation: '46216',
    exposureFactor: 0.75,
  },
  {
    name: 'Ventura Point (C Street)',
    region: 'Ventura',
    latitude: 34.2746,
    longitude: -119.3050,
    orientationDeg: 195,
    breakType: 'point',
    optimalSwellDirMin: 170,
    optimalSwellDirMax: 240,
    optimalWindDir: 'N',
    optimalTideLow: 0.5,
    optimalTideHigh: 4.0,
    nearestTideStation: '9411340',
    nearestBuoyStation: '46216',
    exposureFactor: 0.75,
  },
  {
    name: 'Mondos',
    region: 'Ventura',
    latitude: 34.3527,
    longitude: -119.4348,
    orientationDeg: 195,
    breakType: 'beach',
    optimalSwellDirMin: 170,
    optimalSwellDirMax: 240,
    optimalWindDir: 'N',
    optimalTideLow: 0.0,
    optimalTideHigh: 4.0,
    nearestTideStation: '9411340',
    nearestBuoyStation: '46216',
    exposureFactor: 0.85,
  },
  {
    name: 'Silver Strand',
    region: 'Ventura',
    latitude: 34.1620,
    longitude: -119.2234,
    orientationDeg: 210,
    breakType: 'beach',
    optimalSwellDirMin: 180,
    optimalSwellDirMax: 250,
    optimalWindDir: 'NE',
    optimalTideLow: -0.5,
    optimalTideHigh: 4.0,
    nearestTideStation: '9411340',
    nearestBuoyStation: '46216',
    exposureFactor: 0.85,
  },
  // --- Santa Barbara County ---
  {
    name: 'Leadbetter',
    region: 'Santa Barbara',
    latitude: 34.4049,
    longitude: -119.7105,
    orientationDeg: 180,
    breakType: 'beach',
    optimalSwellDirMin: 160,
    optimalSwellDirMax: 220,
    optimalWindDir: 'N',
    optimalTideLow: 0.0,
    optimalTideHigh: 4.0,
    nearestTideStation: '9411340',
    nearestBuoyStation: '46216',
    exposureFactor: 0.85,
  },
  {
    name: 'Campus Point (UCSB)',
    region: 'Santa Barbara',
    latitude: 34.4076,
    longitude: -119.8434,
    orientationDeg: 195,
    breakType: 'reef',
    optimalSwellDirMin: 170,
    optimalSwellDirMax: 240,
    optimalWindDir: 'N',
    optimalTideLow: 1.0,
    optimalTideHigh: 4.0,
    nearestTideStation: '9411340',
    nearestBuoyStation: '46216',
    exposureFactor: 0.85,
  },
  {
    name: 'Sands Beach (Isla Vista)',
    region: 'Santa Barbara',
    latitude: 34.4086,
    longitude: -119.8776,
    orientationDeg: 200,
    breakType: 'beach',
    optimalSwellDirMin: 170,
    optimalSwellDirMax: 240,
    optimalWindDir: 'N',
    optimalTideLow: -0.5,
    optimalTideHigh: 4.0,
    nearestTideStation: '9411340',
    nearestBuoyStation: '46216',
    exposureFactor: 0.85,
  },
];

// South African surf breaks
// NOAA doesn't cover SA — tide/buoy stations left null, we rely on Open-Meteo
const SA_BREAKS: typeof SOCAL_BREAKS = [
  // --- False Bay / Muizenberg Area ---
  {
    name: 'Muizenberg Beach',
    region: 'Cape Town - False Bay',
    latitude: -34.1088,
    longitude: 18.4735,
    orientationDeg: 180,
    breakType: 'beach',
    optimalSwellDirMin: 150,
    optimalSwellDirMax: 220,
    optimalWindDir: 'N',
    optimalTideLow: 0.0,
    optimalTideHigh: 5.0,
    nearestTideStation: '',
    nearestBuoyStation: '',
    exposureFactor: 0.35,
  },
  {
    name: 'Surfers Corner (Muizenberg)',
    region: 'Cape Town - False Bay',
    latitude: -34.1092,
    longitude: 18.4710,
    orientationDeg: 185,
    breakType: 'beach',
    optimalSwellDirMin: 150,
    optimalSwellDirMax: 230,
    optimalWindDir: 'N',
    optimalTideLow: 0.0,
    optimalTideHigh: 5.0,
    nearestTideStation: '',
    nearestBuoyStation: '',
    exposureFactor: 0.35,
  },
  {
    name: 'Kalk Bay Reef',
    region: 'Cape Town - False Bay',
    latitude: -34.1283,
    longitude: 18.4483,
    orientationDeg: 170,
    breakType: 'reef',
    optimalSwellDirMin: 140,
    optimalSwellDirMax: 210,
    optimalWindDir: 'NW',
    optimalTideLow: 0.5,
    optimalTideHigh: 4.0,
    nearestTideStation: '',
    nearestBuoyStation: '',
    exposureFactor: 0.4,
  },
  {
    name: 'Danger Beach',
    region: 'Cape Town - False Bay',
    latitude: -34.1321,
    longitude: 18.4572,
    orientationDeg: 175,
    breakType: 'beach',
    optimalSwellDirMin: 140,
    optimalSwellDirMax: 210,
    optimalWindDir: 'NW',
    optimalTideLow: 0.0,
    optimalTideHigh: 4.5,
    nearestTideStation: '',
    nearestBuoyStation: '',
    exposureFactor: 0.38,
  },
  {
    name: "St James",
    region: 'Cape Town - False Bay',
    latitude: -34.1178,
    longitude: 18.4590,
    orientationDeg: 180,
    breakType: 'beach',
    optimalSwellDirMin: 150,
    optimalSwellDirMax: 220,
    optimalWindDir: 'NW',
    optimalTideLow: 0.0,
    optimalTideHigh: 5.0,
    nearestTideStation: '',
    nearestBuoyStation: '',
    exposureFactor: 0.35,
  },
  {
    name: 'Clovelly',
    region: 'Cape Town - False Bay',
    latitude: -34.1356,
    longitude: 18.4436,
    orientationDeg: 165,
    breakType: 'beach',
    optimalSwellDirMin: 140,
    optimalSwellDirMax: 200,
    optimalWindDir: 'NW',
    optimalTideLow: 0.0,
    optimalTideHigh: 4.5,
    nearestTideStation: '',
    nearestBuoyStation: '',
    exposureFactor: 0.38,
  },
  // --- Atlantic Seaboard ---
  {
    name: 'Glen Beach',
    region: 'Cape Town - Atlantic',
    latitude: -33.9397,
    longitude: 18.3762,
    orientationDeg: 270,
    breakType: 'beach',
    optimalSwellDirMin: 220,
    optimalSwellDirMax: 310,
    optimalWindDir: 'E',
    optimalTideLow: 0.0,
    optimalTideHigh: 4.0,
    nearestTideStation: '',
    nearestBuoyStation: '',
    exposureFactor: 0.75,
  },
  {
    name: 'Camps Bay',
    region: 'Cape Town - Atlantic',
    latitude: -33.9510,
    longitude: 18.3776,
    orientationDeg: 270,
    breakType: 'beach',
    optimalSwellDirMin: 220,
    optimalSwellDirMax: 310,
    optimalWindDir: 'E',
    optimalTideLow: -0.5,
    optimalTideHigh: 4.0,
    nearestTideStation: '',
    nearestBuoyStation: '',
    exposureFactor: 0.7,
  },
  {
    name: 'Llandudno',
    region: 'Cape Town - Atlantic',
    latitude: -34.0080,
    longitude: 18.3420,
    orientationDeg: 260,
    breakType: 'beach',
    optimalSwellDirMin: 210,
    optimalSwellDirMax: 300,
    optimalWindDir: 'E',
    optimalTideLow: 0.0,
    optimalTideHigh: 4.0,
    nearestTideStation: '',
    nearestBuoyStation: '',
    exposureFactor: 0.8,
  },
  {
    name: 'Dungeons (Hout Bay)',
    region: 'Cape Town - Atlantic',
    latitude: -34.0572,
    longitude: 18.3187,
    orientationDeg: 250,
    breakType: 'reef',
    optimalSwellDirMin: 200,
    optimalSwellDirMax: 290,
    optimalWindDir: 'E',
    optimalTideLow: 1.0,
    optimalTideHigh: 4.0,
    nearestTideStation: '',
    nearestBuoyStation: '',
    exposureFactor: 0.95,
  },
  // --- West Coast / Blouberg ---
  {
    name: 'Big Bay (Blouberg)',
    region: 'Cape Town - West Coast',
    latitude: -33.7980,
    longitude: 18.4570,
    orientationDeg: 270,
    breakType: 'beach',
    optimalSwellDirMin: 220,
    optimalSwellDirMax: 310,
    optimalWindDir: 'E',
    optimalTideLow: 0.0,
    optimalTideHigh: 5.0,
    nearestTideStation: '',
    nearestBuoyStation: '',
    exposureFactor: 0.75,
  },
  {
    name: 'Small Bay (Blouberg)',
    region: 'Cape Town - West Coast',
    latitude: -33.8015,
    longitude: 18.4540,
    orientationDeg: 270,
    breakType: 'beach',
    optimalSwellDirMin: 220,
    optimalSwellDirMax: 310,
    optimalWindDir: 'E',
    optimalTideLow: 0.0,
    optimalTideHigh: 4.5,
    nearestTideStation: '',
    nearestBuoyStation: '',
    exposureFactor: 0.7,
  },
  {
    name: 'Melkbosstrand',
    region: 'Cape Town - West Coast',
    latitude: -33.7180,
    longitude: 18.4470,
    orientationDeg: 270,
    breakType: 'beach',
    optimalSwellDirMin: 220,
    optimalSwellDirMax: 310,
    optimalWindDir: 'E',
    optimalTideLow: -0.5,
    optimalTideHigh: 5.0,
    nearestTideStation: '',
    nearestBuoyStation: '',
    exposureFactor: 0.8,
  },
  // --- South Peninsula / Kommetjie ---
  {
    name: 'Long Beach (Kommetjie)',
    region: 'Cape Town - South Peninsula',
    latitude: -34.1420,
    longitude: 18.3310,
    orientationDeg: 250,
    breakType: 'beach',
    optimalSwellDirMin: 200,
    optimalSwellDirMax: 290,
    optimalWindDir: 'E',
    optimalTideLow: -0.5,
    optimalTideHigh: 5.0,
    nearestTideStation: '',
    nearestBuoyStation: '',
    exposureFactor: 0.85,
  },
  {
    name: 'The Hoek (Kommetjie)',
    region: 'Cape Town - South Peninsula',
    latitude: -34.1365,
    longitude: 18.3198,
    orientationDeg: 240,
    breakType: 'reef',
    optimalSwellDirMin: 200,
    optimalSwellDirMax: 280,
    optimalWindDir: 'SE',
    optimalTideLow: 0.5,
    optimalTideHigh: 3.5,
    nearestTideStation: '',
    nearestBuoyStation: '',
    exposureFactor: 0.8,
  },
  {
    name: 'Outer Kom',
    region: 'Cape Town - South Peninsula',
    latitude: -34.1395,
    longitude: 18.3160,
    orientationDeg: 245,
    breakType: 'reef',
    optimalSwellDirMin: 200,
    optimalSwellDirMax: 280,
    optimalWindDir: 'SE',
    optimalTideLow: 1.0,
    optimalTideHigh: 3.5,
    nearestTideStation: '',
    nearestBuoyStation: '',
    exposureFactor: 0.85,
  },
  {
    name: 'Noordhoek Beach',
    region: 'Cape Town - South Peninsula',
    latitude: -34.1050,
    longitude: 18.3660,
    orientationDeg: 260,
    breakType: 'beach',
    optimalSwellDirMin: 210,
    optimalSwellDirMax: 300,
    optimalWindDir: 'E',
    optimalTideLow: -0.5,
    optimalTideHigh: 5.0,
    nearestTideStation: '',
    nearestBuoyStation: '',
    exposureFactor: 0.8,
  },
  {
    name: 'Scarborough',
    region: 'Cape Town - South Peninsula',
    latitude: -34.1970,
    longitude: 18.3720,
    orientationDeg: 220,
    breakType: 'beach',
    optimalSwellDirMin: 180,
    optimalSwellDirMax: 270,
    optimalWindDir: 'SE',
    optimalTideLow: 0.0,
    optimalTideHigh: 4.5,
    nearestTideStation: '',
    nearestBuoyStation: '',
    exposureFactor: 0.75,
  },
  // --- Garden Route / Eastern Cape ---
  {
    name: 'Jeffreys Bay (Supertubes)',
    region: 'Eastern Cape',
    latitude: -33.9580,
    longitude: 25.9340,
    orientationDeg: 135,
    breakType: 'point',
    optimalSwellDirMin: 120,
    optimalSwellDirMax: 200,
    optimalWindDir: 'W',
    optimalTideLow: 0.5,
    optimalTideHigh: 4.0,
    nearestTideStation: '',
    nearestBuoyStation: '',
    exposureFactor: 0.9,
  },
  {
    name: 'Jeffreys Bay (Kitchen Windows)',
    region: 'Eastern Cape',
    latitude: -33.9530,
    longitude: 25.9280,
    orientationDeg: 140,
    breakType: 'point',
    optimalSwellDirMin: 120,
    optimalSwellDirMax: 200,
    optimalWindDir: 'W',
    optimalTideLow: 1.0,
    optimalTideHigh: 4.5,
    nearestTideStation: '',
    nearestBuoyStation: '',
    exposureFactor: 0.85,
  },
  {
    name: 'Seal Point (Cape St Francis)',
    region: 'Eastern Cape',
    latitude: -34.2070,
    longitude: 24.8360,
    orientationDeg: 150,
    breakType: 'point',
    optimalSwellDirMin: 130,
    optimalSwellDirMax: 210,
    optimalWindDir: 'NW',
    optimalTideLow: 0.5,
    optimalTideHigh: 4.0,
    nearestTideStation: '',
    nearestBuoyStation: '',
    exposureFactor: 0.85,
  },
  // --- KwaZulu-Natal ---
  {
    name: 'New Pier (Durban)',
    region: 'KwaZulu-Natal',
    latitude: -29.8600,
    longitude: 31.0490,
    orientationDeg: 90,
    breakType: 'beach',
    optimalSwellDirMin: 60,
    optimalSwellDirMax: 150,
    optimalWindDir: 'W',
    optimalTideLow: -0.5,
    optimalTideHigh: 5.0,
    nearestTideStation: '',
    nearestBuoyStation: '',
    exposureFactor: 0.75,
  },
  {
    name: 'Cave Rock (Durban)',
    region: 'KwaZulu-Natal',
    latitude: -29.9050,
    longitude: 31.0320,
    orientationDeg: 100,
    breakType: 'reef',
    optimalSwellDirMin: 70,
    optimalSwellDirMax: 160,
    optimalWindDir: 'W',
    optimalTideLow: 0.5,
    optimalTideHigh: 4.0,
    nearestTideStation: '',
    nearestBuoyStation: '',
    exposureFactor: 0.8,
  },
  {
    name: 'Ballito',
    region: 'KwaZulu-Natal',
    latitude: -29.5360,
    longitude: 31.2180,
    orientationDeg: 90,
    breakType: 'beach',
    optimalSwellDirMin: 50,
    optimalSwellDirMax: 150,
    optimalWindDir: 'W',
    optimalTideLow: 0.0,
    optimalTideHigh: 5.0,
    nearestTideStation: '',
    nearestBuoyStation: '',
    exposureFactor: 0.75,
  },
  // --- West Coast (outside Cape Town) ---
  {
    name: 'Elands Bay',
    region: 'West Coast',
    latitude: -32.3100,
    longitude: 18.3250,
    orientationDeg: 270,
    breakType: 'point',
    optimalSwellDirMin: 220,
    optimalSwellDirMax: 310,
    optimalWindDir: 'E',
    optimalTideLow: 0.5,
    optimalTideHigh: 4.0,
    nearestTideStation: '',
    nearestBuoyStation: '',
    exposureFactor: 0.85,
  },
];

async function seed() {
  console.log('Seeding breaks database...');

  // Delete dependent rows first, then breaks (idempotent)
  await db.delete(conditions).execute();
  await db.delete(userBreaks).execute();
  await db.delete(breaks).execute();

  const allBreaks = [...SOCAL_BREAKS, ...SA_BREAKS];

  const records = allBreaks.map((b) => ({
    id: nanoid(),
    ...b,
  }));

  await db.insert(breaks).values(records).execute();

  console.log(`Seeded ${records.length} surf breaks (${SOCAL_BREAKS.length} SoCal + ${SA_BREAKS.length} South Africa).`);

  // Verify
  const count = await db.select({ count: sql<number>`count(*)` }).from(breaks);
  console.log(`Verified: ${count[0].count} breaks in database.`);
}

seed().catch(console.error);
